-- ============================================================================
-- LEGACY MIGRATION — INTENTIONALLY NO-OP
-- ============================================================================
--
-- This migration was created on 2026-06-27 during the very first setup of the
-- backend on the EC2 server, before the repo was cleaned up and squashed into
-- `20260101000000_baseline_init`.
--
-- Both migrations are recorded in the production `_prisma_migrations` table.
-- Prisma never replays applied migrations against a real DB, so on prod this
-- file is never read. However, `prisma migrate dev` uses a fresh shadow DB
-- to verify migration consistency, and there the SQL from BOTH migrations
-- would run. Since `baseline_init` already creates every enum and table this
-- file used to create, we get "type already exists" errors on the shadow DB.
--
-- Fix: strip this file's SQL entirely. Prisma still tracks the migration by
-- name (folder must stay, checksum stays stable), but replaying it becomes a
-- no-op. Safe on prod (row already exists in _prisma_migrations, never re-runs)
-- and on every dev laptop (marked as applied via `prisma migrate resolve
-- --applied 20260627110143_init` when the folder was first pulled).
--
-- The original SQL is preserved alongside this file as `migration.sql.original.bak`
-- for historical reference — do not commit it (add to .gitignore if you want
-- to keep it locally).
--
-- If you're setting up a brand new dev DB from scratch (rare), you'll need to
-- run `npx prisma migrate resolve --applied 20260627110143_init` before running
-- `migrate dev`, since the shadow DB validation will still count this folder.
-- ============================================================================

SELECT 1;
